/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsSessionIdRouteImport } from './routes/results.$sessionId'
import { Route as LobbySessionIdRouteImport } from './routes/lobby.$sessionId'
import { Route as GameSessionIdRouteImport } from './routes/game.$sessionId'
import { Route as ApiGameJoinRouteImport } from './routes/api/game/join'
import { Route as ApiGameHostRouteImport } from './routes/api/game/host'
import { Route as ApiGameCreateRouteImport } from './routes/api/game/create'
import { Route as ApiGameActionRouteImport } from './routes/api/game/action'
import { Route as ApiGameStateSessionIdRouteImport } from './routes/api/game/state.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSessionIdRoute = ResultsSessionIdRouteImport.update({
  id: '/results/$sessionId',
  path: '/results/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbySessionIdRoute = LobbySessionIdRouteImport.update({
  id: '/lobby/$sessionId',
  path: '/lobby/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSessionIdRoute = GameSessionIdRouteImport.update({
  id: '/game/$sessionId',
  path: '/game/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameJoinRoute = ApiGameJoinRouteImport.update({
  id: '/api/game/join',
  path: '/api/game/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameHostRoute = ApiGameHostRouteImport.update({
  id: '/api/game/host',
  path: '/api/game/host',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameCreateRoute = ApiGameCreateRouteImport.update({
  id: '/api/game/create',
  path: '/api/game/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameActionRoute = ApiGameActionRouteImport.update({
  id: '/api/game/action',
  path: '/api/game/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameStateSessionIdRoute = ApiGameStateSessionIdRouteImport.update({
  id: '/api/game/state/$sessionId',
  path: '/api/game/state/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$sessionId': typeof GameSessionIdRoute
  '/lobby/$sessionId': typeof LobbySessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/api/game/action': typeof ApiGameActionRoute
  '/api/game/create': typeof ApiGameCreateRoute
  '/api/game/host': typeof ApiGameHostRoute
  '/api/game/join': typeof ApiGameJoinRoute
  '/api/game/state/$sessionId': typeof ApiGameStateSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$sessionId': typeof GameSessionIdRoute
  '/lobby/$sessionId': typeof LobbySessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/api/game/action': typeof ApiGameActionRoute
  '/api/game/create': typeof ApiGameCreateRoute
  '/api/game/host': typeof ApiGameHostRoute
  '/api/game/join': typeof ApiGameJoinRoute
  '/api/game/state/$sessionId': typeof ApiGameStateSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$sessionId': typeof GameSessionIdRoute
  '/lobby/$sessionId': typeof LobbySessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/api/game/action': typeof ApiGameActionRoute
  '/api/game/create': typeof ApiGameCreateRoute
  '/api/game/host': typeof ApiGameHostRoute
  '/api/game/join': typeof ApiGameJoinRoute
  '/api/game/state/$sessionId': typeof ApiGameStateSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game/$sessionId'
    | '/lobby/$sessionId'
    | '/results/$sessionId'
    | '/api/game/action'
    | '/api/game/create'
    | '/api/game/host'
    | '/api/game/join'
    | '/api/game/state/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game/$sessionId'
    | '/lobby/$sessionId'
    | '/results/$sessionId'
    | '/api/game/action'
    | '/api/game/create'
    | '/api/game/host'
    | '/api/game/join'
    | '/api/game/state/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/game/$sessionId'
    | '/lobby/$sessionId'
    | '/results/$sessionId'
    | '/api/game/action'
    | '/api/game/create'
    | '/api/game/host'
    | '/api/game/join'
    | '/api/game/state/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameSessionIdRoute: typeof GameSessionIdRoute
  LobbySessionIdRoute: typeof LobbySessionIdRoute
  ResultsSessionIdRoute: typeof ResultsSessionIdRoute
  ApiGameActionRoute: typeof ApiGameActionRoute
  ApiGameCreateRoute: typeof ApiGameCreateRoute
  ApiGameHostRoute: typeof ApiGameHostRoute
  ApiGameJoinRoute: typeof ApiGameJoinRoute
  ApiGameStateSessionIdRoute: typeof ApiGameStateSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$sessionId': {
      id: '/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof ResultsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$sessionId': {
      id: '/lobby/$sessionId'
      path: '/lobby/$sessionId'
      fullPath: '/lobby/$sessionId'
      preLoaderRoute: typeof LobbySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$sessionId': {
      id: '/game/$sessionId'
      path: '/game/$sessionId'
      fullPath: '/game/$sessionId'
      preLoaderRoute: typeof GameSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/join': {
      id: '/api/game/join'
      path: '/api/game/join'
      fullPath: '/api/game/join'
      preLoaderRoute: typeof ApiGameJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/host': {
      id: '/api/game/host'
      path: '/api/game/host'
      fullPath: '/api/game/host'
      preLoaderRoute: typeof ApiGameHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/create': {
      id: '/api/game/create'
      path: '/api/game/create'
      fullPath: '/api/game/create'
      preLoaderRoute: typeof ApiGameCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/action': {
      id: '/api/game/action'
      path: '/api/game/action'
      fullPath: '/api/game/action'
      preLoaderRoute: typeof ApiGameActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/state/$sessionId': {
      id: '/api/game/state/$sessionId'
      path: '/api/game/state/$sessionId'
      fullPath: '/api/game/state/$sessionId'
      preLoaderRoute: typeof ApiGameStateSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameSessionIdRoute: GameSessionIdRoute,
  LobbySessionIdRoute: LobbySessionIdRoute,
  ResultsSessionIdRoute: ResultsSessionIdRoute,
  ApiGameActionRoute: ApiGameActionRoute,
  ApiGameCreateRoute: ApiGameCreateRoute,
  ApiGameHostRoute: ApiGameHostRoute,
  ApiGameJoinRoute: ApiGameJoinRoute,
  ApiGameStateSessionIdRoute: ApiGameStateSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
